Initial commit
utopia-rise/godot-kotlin-native-project-template pull request #1
Opened 2020-03-06 22:03 UTC by Wavesonics

2020-03-09 23:57 UTC, Wavesonics commented
This is ready to merge now.

I updated the README explaining what it is and how to use it.

2020-03-10 15:51 UTC, chippmann requested changes
Thanks a lot for your work!
Some minor changes needed in my opinion but otherwise great!

2020-03-10 15:51 UTC, chippmann commented on .gitignore
> +.gradle/*
The .gitignore laks all the intellij specific ignores
I think we can safely assume the user to use intellij or eclipse to use so i think we should add those gitignore entries as well. I would take it from here: http://gitignore.io/

2020-03-10 15:51 UTC, chippmann commented on runBuild
> +./gradlew build
I would add comments on why those files are needed

2020-03-10 15:51 UTC, chippmann commented on runBuild.bat
> +call gradlew.bat build
I would add comments on why those files are needed

2020-03-10 19:14 UTC, Wavesonics commented on runBuild.bat
> +call gradlew.bat build
Solved in 5b1cfec

2020-03-10 19:14 UTC, Wavesonics commented on runBuild
> +./gradlew build
Solved in 5b1cfec

2020-03-10 19:14 UTC, Wavesonics commented on .gitignore
> +.gradle/*
Solved in 52f8757

2020-03-11 07:13 UTC, chippmann approved these changes
Thanks a lot for the implementation!

2020-03-11 07:14 UTC, merged